export const industriesData = [
    {
        title: "Information Technology",
        slug: "information-technology",
        description: "Software engineers, product managers, data scientists, and tech leaders.",
        longDescription: "The Information Technology sector is the backbone of modern business. We specialize in finding top-tier talent for software development, cybersecurity, data science, and IT infrastructure. Our candidates are innovators who drive digital transformation.",
        challenges: ["Rapidly evolving tech stack", "High competition for top talent", "Cybersecurity threats"],
        solutions: ["Access to a global talent pool", " rigorous technical screening", "Focus on cultural fit"],
        placements: "2000+",
        bg: "images/bg1.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/3067/3067451.png"
    },
    {
        title: "Healthcare",
        slug: "healthcare",
        description: "Medical experts, innovators, and compliance leaders making quality care accessible.",
        longDescription: "Healthcare recruitment requires a deep understanding of medical qualifications and regulatory standards. We connect healthcare providers with doctors, nurses, administrators, and allied health professionals who are dedicated to patient care.",
        challenges: ["Shortage of qualified professionals", "Burnout and retention", "Regulatory compliance"],
        solutions: ["Targeted recruitment strategies", "Support for licensing and credentialing", "Emphasis on work-life balance"],
        placements: "800+",
        bg: "images/bg4.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/2966/2966334.png"
    },
    {
        title: "Finance",
        slug: "finance",
        description: "Banking, insurance, fintech, and investment professionals who drive stability and growth.",
        longDescription: "In the fast-paced world of finance, precision and integrity are paramount. We recruit for banking, investment, fintech, and insurance sectors, identifying professionals who can navigate complex financial landscapes.",
        challenges: ["Regulatory changes", "Data security", "Digital disruption"],
        solutions: ["Expertise in financial regulations", "Vetting for integrity and skill", "Focus on fintech innovators"],
        placements: "1000+",
        bg: "images/bg5.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/2704/2704332.png"
    },
    {
        title: "Education",
        slug: "education",
        description: "Educators, administrators, and support staff shaping the future of learning.",
        longDescription: "Education is the foundation of society. We help schools, universities, and ed-tech companies find passionate educators, administrators, and support staff who are committed to student success.",
        challenges: ["Teacher shortages", "Adapting to remote learning", "Budget constraints"],
        solutions: ["Global recruitment for educators", "Digital literacy assessment", "Cost-effective hiring solutions"],
        placements: "500+",
        bg: "images/bg6.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/2232/2232688.png"
    },
    {
        title: "Manufacturing",
        slug: "manufacturing",
        description: "Mechanical, electrical, industrial engineers, and production managers who optimize operations.",
        longDescription: "Manufacturing drives the economy. We source engineers, production managers, and skilled tradespeople who optimize production lines, ensure quality, and drive operational efficiency.",
        challenges: ["Skill gap in advanced manufacturing", "Supply chain disruptions", "Workplace safety"],
        solutions: ["Upskilling programs", "Agile workforce planning", "Safety-first recruitment"],
        placements: "1200+",
        bg: "images/bg1.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/2083/2083239.png"
    },
    {
        title: "Retail",
        slug: "retail",
        description: "Digital marketing, operations, supply chain, and customer experience professionals.",
        longDescription: "Retail is all about customer experience. We help brands find store managers, merchandisers, supply chain experts, and customer service stars who can deliver exceptional service and drive sales.",
        challenges: ["High turnover rates", "E-commerce competition", "Changing consumer behavior"],
        solutions: ["Volume hiring capabilities", "Focus on customer-centric skills", "Omnichannel talent sourcing"],
        placements: "1500+",
        bg: "images/bg2.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/1170/1170679.png"
    },
    {
        title: "Hospitality",
        slug: "hospitality",
        description: "Professionals dedicated to providing exceptional guest experiences and service.",
        longDescription: "The hospitality industry thrives on service. We recruit for hotels, restaurants, and travel companies, finding staff who are hospitable, professional, and dedicated to creating memorable experiences.",
        challenges: ["Seasonal demand fluctuations", "Staff retention", "Service quality consistency"],
        solutions: ["Flexible staffing models", "Training and development focus", " rigorous vetting for soft skills"],
        placements: "600+",
        bg: "images/bg8.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/201/201623.png"
    },
    {
        title: "Real Estate",
        slug: "real-estate",
        description: "Strategic leaders in development, sales, marketing, and investment who deliver measurable returns.",
        longDescription: "Real estate requires a mix of sales acumen and market knowledge. We connect agencies and developers with agents, property managers, and investment analysts who can close deals and manage assets.",
        challenges: ["Market volatility", "Regulatory hurdles", "High competition"],
        solutions: ["Headhunting top performers", "Specialized market knowledge", "Confidential executive search"],
        placements: "500+",
        bg: "images/bg8.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/609/609803.png"
    },
    {
        title: "Automotive",
        slug: "automotive",
        description: "Experts in design, manufacturing, and sales driving the automotive industry forward.",
        longDescription: "The automotive industry is in a state of rapid evolution with EVs and autonomous driving. We recruit engineers, designers, and sales professionals who are at the forefront of this innovation.",
        challenges: ["Shift to electric vehicles", "Supply chain complexity", "Technical skill shortages"],
        solutions: ["Sourcing specialized EV talent", "Global search for engineers", "Partnerships with technical institutes"],
        placements: "400+",
        bg: "images/bg5.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/2311/2311491.png"
    },
    {
        title: "Telecommunications",
        slug: "telecommunications",
        description: "Connecting the world through advanced network and communication solutions.",
        longDescription: "Telecommunications connect the world. We find network engineers, technicians, and project managers who build and maintain the infrastructure that keeps us all connected.",
        challenges: ["5G rollout", "Network security", "Infrastructure maintenance"],
        solutions: ["Technical assessment of network skills", "Rapid deployment teams", "Focus on certified professionals"],
        placements: "700+",
        bg: "images/bg4.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/3253/3253234.png"
    },
    {
        title: "Energy",
        slug: "energy",
        description: "Visionary leaders in solar, wind, and clean energy who drive sustainability.",
        longDescription: "The energy sector is powering the future. We specialize in renewables, oil & gas, and utilities, recruiting engineers, project managers, and safety experts committed to powering the world.",
        challenges: ["Transition to renewables", "Regulatory compliance", "Remote project locations"],
        solutions: ["Sourcing for green energy skills", "Global mobility support", "Safety-critical recruitment"],
        placements: "500+",
        bg: "images/bg6.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/2933/2933880.png"
    },
    {
        title: "Logistics & Supply Chain",
        slug: "logistics-supply-chain",
        description: "Professionals ensuring your operations run on time, on budget, and without disruption.",
        longDescription: "Efficient logistics are the lifeblood of commerce. We recruit supply chain managers, logistics coordinators, and fleet managers who ensure goods move smoothly and efficiently.",
        challenges: ["Global supply chain disruptions", "Last-mile delivery costs", "Digitalization of logistics"],
        solutions: ["Experts in supply chain optimization", "Tech-savvy logistics talent", "Agile staffing solutions"],
        placements: "700+",
        bg: "images/bg7.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/759/759041.png"
    },
    {
        title: "E-commerce",
        slug: "e-commerce",
        description: "Digital marketing, operations, supply chain, and customer experience professionals.",
        longDescription: "E-commerce is booming. We help online retailers find digital marketers, e-commerce managers, and fulfillment experts who can drive online sales and manage operations.",
        challenges: ["Intense competition", "Customer acquisition costs", "Logistics complexity"],
        solutions: ["Data-driven marketing talent", "E-commerce platform experts", "Scalable hiring for peak seasons"],
        placements: "1500+",
        bg: "images/bg2.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/3081/3081559.png"
    },
    {
        title: "Marketing & Advertising",
        slug: "marketing-advertising",
        description: "Creative minds and strategic planners elevating brand presence and reach.",
        longDescription: "Creativity meets strategy in marketing. We source brand managers, digital marketers, content creators, and ad specialists who can build brands and drive engagement.",
        challenges: ["Digital noise", "Measuring ROI", "Keeping up with trends"],
        solutions: ["Creative portfolio reviews", "Data-savvy marketing starts", "Trend-focused talent sourcing"],
        placements: "1100+",
        bg: "images/bg8.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/1998/1998087.png"
    },
    {
        title: "Construction",
        slug: "construction",
        description: "Build robust infrastructure with top-tier project managers and engineers.",
        longDescription: "Construction builds our world. We recruit project managers, site engineers, architects, and skilled labor for residential, commercial, and infrastructure projects.",
        challenges: ["Labor shortages", "Project delays", "Safety regulations"],
        solutions: ["Access to skilled tradespeople", "Project management experts", "Safety-focused hiring"],
        placements: "600+",
        bg: "images/bg1.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/3022/3022319.png"
    },
    {
        title: "Pharmaceuticals",
        slug: "pharmaceuticals",
        description: "Innovators in drug development and patient care transforming healthcare.",
        longDescription: "Pharmaceuticals require scientific excellence. We connect pharma companies with researchers, clinical trial managers, and sales representatives who are advancing medical science.",
        challenges: ["Long R&D cycles", "Regulatory scrutiny", "Patent cliffs"],
        solutions: ["PhD-level talent sourcing", "Regulatory affairs experts", "Sales teams with scientific background"],
        placements: "450+",
        bg: "images/bg4.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/883/883407.png"
    },
    {
        title: "Media & Entertainment",
        slug: "media-entertainment",
        description: "Content creators, marketers, and storytellers who inspire audiences.",
        longDescription: "Entertainment inspires us. We recruit for film, TV, digital media, and gaming, finding creative talent, production staff, and business executives who bring stories to life.",
        challenges: ["Digital distribution shifts", "Content piracy", "Monetization models"],
        solutions: ["Creative talent networks", "Digital rights experts", "Business development leaders"],
        placements: "1500+",
        bg: "images/bg8.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/3163/3163478.png"
    },
    {
        title: "Insurance",
        slug: "insurance",
        description: "Risk management experts proving security and peace of mind.",
        longDescription: "Insurance provides security. We find underwriters, claims adjusters, actuaries, and sales agents who help individuals and businesses manage risk.",
        challenges: ["Risk modeling complexity", "Digital transformation", "Customer trust"],
        solutions: ["Actuarial talent search", "Insurtech experts", "Customer-centric agents"],
        placements: "800+",
        bg: "images/bg5.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/2666/2666505.png"
    },
    {
        title: "Legal Services",
        slug: "legal-services",
        description: "Legal professionals advocating for justice and corporate compliance.",
        longDescription: "Law upholds justice and commerce. We recruit attorneys, paralegals, and compliance officers for law firms and corporate legal departments.",
        challenges: ["High caseloads", "Regulatory complexity", "Talent retention"],
        solutions: ["Specialized legal recruiters", "Confidential partner search", "Legal support staffing"],
        placements: "300+",
        bg: "images/bg6.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/2452/2452286.png"
    },
    {
        title: "Human Resources",
        slug: "human-resources",
        description: "HR leaders managing talent, culture, and organizational growth.",
        longDescription: "People are a company's greatest asset. We recruit HR managers, recruiters, talent acquisition specialists, and benefits administrators who build great cultures.",
        challenges: ["Talent acquisition wars", "Employee engagement", "Remote work policies"],
        solutions: ["HR tech experts", "Culture-focused HR leaders", "Strategic talent partners"],
        placements: "900+",
        bg: "images/bg2.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/942/942799.png"
    },
    {
        title: "Banking",
        slug: "banking",
        description: "Experts in financial management, lending, and asset protection.",
        longDescription: "Banking is the engine of the economy. We recruit bankers, loan officers, branch managers, and risk analysts who ensure financial stability and growth.",
        challenges: ["Digital banking shift", "Compliance costs", "Cybersecurity"],
        solutions: ["Digital banking talent", "Compliance officers", "Customer relationship managers"],
        placements: "1000+",
        bg: "images/bg5.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/2830/2830284.png"
    },
    {
        title: "Food & Beverage",
        slug: "food-beverage",
        description: "Culinary and management professionals delivering taste and quality.",
        longDescription: "F&B brings people together. We recruit chefs, restaurant managers, food scientists, and quality assurance specialists for the food and beverage industry.",
        challenges: ["Supply chain safety", "Consumer trends", "Labor costs"],
        solutions: ["Culinary talent scouting", "Food safety experts", "Efficient operations managers"],
        placements: "550+",
        bg: "images/bg7.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/3014/3014521.png"
    },
    {
        title: "Aerospace & Defense",
        slug: "aerospace-defense",
        description: "Engineers and specialists advancing aviation and national security.",
        longDescription: "Aerospace touches the skies. We recruit aerospace engineers, avionics technicians, and defense contractors who work on cutting-edge aviation and security technology.",
        challenges: ["High security clearance needs", "Technological complexity", "Long project timelines"],
        solutions: ["Security-cleared talent", "Specialized engineering search", "Project lifecycle support"],
        placements: "200+",
        bg: "images/bg1.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/1063/1063376.png"
    },
    {
        title: "Agriculture",
        slug: "agriculture",
        description: "Professionals enhancing food production and sustainable farming practices.",
        longDescription: "Agriculture feeds the world. We recruit for agritech, farm management, and food production, finding professionals who are modernizing agriculture.",
        challenges: ["Climate change impact", "Labor availability", "Technological adoption"],
        solutions: ["Agritech specialists", "Sustainable farming experts", "Rural recruitment networks"],
        placements: "300+",
        bg: "images/bg4.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/2829/2829824.png"
    },
    {
        title: "Chemicals",
        slug: "chemicals",
        description: "Scientists and engineers driving innovation in chemical processes.",
        longDescription: "The chemical industry provides essential materials. We recruit chemical engineers, lab technicians, and process safety experts who ensure safe and efficient production.",
        challenges: ["Safety regulations", "Environmental impact", "Process efficiency"],
        solutions: ["Safety-certified professionals", "Green chemistry experts", "Process optimization engineers"],
        placements: "400+",
        bg: "images/bg6.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/1004/1004948.png"
    },
    {
        title: "Consulting",
        slug: "consulting",
        description: "Strategic advisors helping businesses solve complex problems.",
        longDescription: "Consultants drive change. We recruit management consultants, strategy analysts, and implementation specialists who help organizations solve their toughest challenges.",
        challenges: ["High client expectations", "Travel requirements", "Burnout"],
        solutions: ["Top-tier MBA recruitment", "Work-life balance focus", "Diverse skill set sourcing"],
        placements: "800+",
        bg: "images/bg2.png",
        text: "text-[#FFFFFF]",
        img: "https://cdn-icons-png.flaticon.com/512/912/912318.png"
    },
    {
        title: "Gaming",
        slug: "gaming",
        description: "Developers, designers, and testers creating immersive gaming experiences.",
        longDescription: "Gaming is entertainment evolved. We recruit game developers, artists, level designers, and QA testers who create the games played by millions.",
        challenges: ["Crunch culture", "Rapid tech changes", "User acquisition"],
        solutions: ["Passion-driven recruitment", "Remote work options", "Creative portfolio assessment"],
        placements: "500+",
        bg: "images/bg8.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/686/686589.png"
    },
    {
        title: "Biotechnology",
        slug: "biotechnology",
        description: "Researchers and scientists pushing the boundaries of biological science.",
        longDescription: "Biotech improves lives. We recruit biotechnologists, researchers, and lab managers who are working on breakthroughs in medicine, agriculture, and industry.",
        challenges: ["Funding uncertainty", "Regulatory pathways", "Specialized skill needs"],
        solutions: ["PhD recruitment networks", "Grant writing support", "Lab management talent"],
        placements: "350+",
        bg: "images/bg4.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/2082/2082878.png"
    },
    {
        title: "Non-Profit",
        slug: "non-profit",
        description: "Passionate individuals dedicated to social impact and community service.",
        longDescription: "Non-profits change the world. We recruit fundraisers, program directors, and volunteer coordinators who are driven by mission and impact.",
        challenges: ["Funding limits", "Volunteer management", "Measuring impact"],
        solutions: ["Mission-aligned hiring", "Volunteer coordination experts", "Grant writing talent"],
        placements: "250+",
        bg: "images/bg5.png",
        text: "text-[#1B084C]",
        img: "https://cdn-icons-png.flaticon.com/512/3209/3209265.png"
    }
];
