export const industries = [
    "Information Technology",
    "Healthcare",
    "Finance",
    "Education",
    "Manufacturing",
    "Retail",
    "Hospitality",
    "Real Estate",
    "Automotive",
    "Telecommunications",
    "Energy",
    "Logistics & Supply Chain",
    "E-commerce",
    "Marketing & Advertising",
    "Construction",
    "Pharmaceuticals",
    "Media & Entertainment",
    "Insurance",
    "Legal Services",
    "Human Resources",
    "Banking",
    "Food & Beverage",
    "Aerospace & Defense",
    "Agriculture",
    "Chemicals",
    "Consulting",
    "Gaming",
    "Biotechnology",
    "Non-Profit",
];
